# Generated by Django 4.1.3 on 2023-04-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_registration_usertype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
