# Generated by Django 4.1.3 on 2023-04-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
