# Generated by Django 4.1.3 on 2023-04-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Registration",
        ),
    ]
