# Generated by Django 4.1.3 on 2023-05-01 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="doc_id",
            field=models.ForeignKey(
                db_column="doc_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="main.registration",
            ),
        ),
    ]
