# Generated by Django 4.1.3 on 2023-05-01 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_blog_content_alter_blog_summary"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
