# Generated by Django 4.1.3 on 2023-05-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_delete_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_column="title", max_length=20)),
                ("category", models.CharField(db_column="cat", max_length=20)),
                ("summary", models.TextField(db_column="sum", max_length=50)),
                ("content", models.TextField(db_column="content", max_length=500)),
                ("blogimage", models.ImageField(upload_to="images/")),
                (
                    "doc_id",
                    models.ForeignKey(
                        db_column="doc_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.registration",
                    ),
                ),
            ],
            options={
                "db_table": "blog",
            },
        ),
    ]
